Bouncemgt
phpList/phplist3 pull request #1028
Opened 2024-03-05 20:56 UTC by lwcorp

## Description
1. Added support for processing bounces without downloading new bounces (great for testing rules!)
1. Added support for a new bounce rule action that allows defining cases when that should undo automatic actions (this connects to point 1 when you accidentally unconfirm subscribers and wish to test how not to do it again without affecting bounces that were to be affected since they weren't downloaded yet)

## Screenshots (if appropriate):
![image](https://github.com/phpList/phplist3/assets/1773306/918a7c8f-ef16-4c6e-9e47-df04aba12327)
![image](https://github.com/phpList/phplist3/assets/1773306/bf8cb98f-880a-4247-a708-f444a5e7043d)

2024-03-05 21:42 UTC, lwcorp commented
Not sure why it failed a syntax check - **Named Arguments** have been supported [since at least PHP 8.0.0]((https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments)), while [phpList requires 8.1](https://resources.phplist.com/system/start#phplist_system_requirements).

See:
![image](https://github.com/phpList/phplist3/assets/1773306/8ee0983b-84a8-47e2-a899-0a5d6c2c1899)
![image](https://github.com/phpList/phplist3/assets/1773306/27df21ad-6815-48b1-ab16-288fecc9c4a2)

2024-03-09 11:51 UTC, michield requested changes

2024-03-09 11:51 UTC, michield commented on public_html/lists/admin/bouncemgt.php
> +echo $spb.PageLink2('processbounces&justexisting=true', s('Reprocess Only Existing Bounces'), title: s('Reprocess Only Existing Bounces')).$spe;
Yes, I'm also not sure why the CI is failing on this, but to make things easier, maybe just take the named argument out.

2024-03-09 11:51 UTC, michield commented on public_html/lists/admin/processbounces.php
> +if (isset($_GET['justexisting']))
Wow, a "goto". That's a blast from the past. It works, but I think it's neater and better readable to just put an if-then. 

Also, curly brackets will be good to add.

2024-03-09 11:51 UTC, michield commented on public_html/lists/admin/processbounces.php
> +                            $GLOBALS['tables']['user'], '-1', $row['user']));
Why not just 

```
Sql_Query(sprintf('update %s set bouncecount = bouncecount -1  where id = %d',
                            $GLOBALS['tables']['user'], $row['user']));
```

2024-03-09 19:08 UTC, lwcorp commented on public_html/lists/admin/bouncemgt.php
> +echo $spb.PageLink2('processbounces&justexisting=true', s('Reprocess Only Existing Bounces'), title: s('Reprocess Only Existing Bounces')).$spe;
I rather not as the alternative is to **hardcode** no less than 2 of the (currently) default values of function PageLink2 ($url and $no_plugin). If these defaults are changed in the future from blank to something else, I doubt anyone will remember to update this specific call.
What do you think?

2024-03-09 19:19 UTC, lwcorp commented on public_html/lists/admin/processbounces.php
> +if (isset($_GET['justexisting']))
It was done in order to highlight just the new feature instead of modifying existing code (adding spaces is still modifying).
But now done as you requested.

2024-03-09 19:20 UTC, lwcorp commented on public_html/lists/admin/processbounces.php
> +                            $GLOBALS['tables']['user'], '-1', $row['user']));
It was done to so it can be easily modifiable in the value passed to sprintf.
But I guess -1 is less likely to be needed to change, so done as requested.

2024-03-10 08:59 UTC, michield commented on public_html/lists/admin/bouncemgt.php
> +echo $spb.PageLink2('processbounces&justexisting=true', s('Reprocess Only Existing Bounces'), title: s('Reprocess Only Existing Bounces')).$spe;
Well, the other option is to figure out why the CI is failing. Maybe it's some option in phplint that needs to be enabled. 

https://github.com/phpList/phplist3/actions/runs/8216684807/job/22471522555?pr=1028#step:11:1

But what's wrong with following the pattern of the other links and just using

`echo $spb.PageLink2('processbounces&justexisting=true', s('Reprocess Only Existing Bounces')).$spe;`

2024-03-10 09:02 UTC, michield commented on public_html/lists/admin/bouncemgt.php
> +echo $spb.PageLink2('processbounces&justexisting=true', s('Reprocess Only Existing Bounces'), title: s('Reprocess Only Existing Bounces')).$spe;
Ah, I see the answer to that last question. It uses the same title as the main processbounces.

That is because it uses a special mechanism in the translation system, see https://resources.phplist.com/translations/start

Looks for `pagetitle: ` and `pagetitlehover:`

2024-03-10 09:18 UTC, michield commented on public_html/lists/admin/bouncemgt.php
> +echo $spb.PageLink2('processbounces&justexisting=true', s('Reprocess Only Existing Bounces'), title: s('Reprocess Only Existing Bounces')).$spe;
The linter used is https://github.com/overtrue/phplint

2024-03-10 10:55 UTC, bramley commented
I have just seen the comment about requiring php 8.1 or later. That is not a hard-requirement and I still know of people using php 7.  Using named parameters is going to make the page unavailable in these cases.

The only reference in the code to a required version seems to be php 5.3.

    if (version_compare(PHP_VERSION, '5.3.3', '<') && WARN_ABOUT_PHP_SETTINGS) {
        Error(s('Your PHP version is out of date. phpList requires PHP version 5.3.3 or higher.'));
    }

2024-03-10 13:48 UTC, michield commented
Yes, I wonder if we need to at least require 7.4 or something, but even [7.4 is EOL](https://endoflife.date/php).

2024-03-11 00:25 UTC, lwcorp commented
Fine, I've made it version dependent. Users who use EOL versions will get hardcoded default values. If those values ever change, users with non EOL versions will get the new default values.

2024-03-11 07:35 UTC, bramley commented
There is a syntax error in the latest change.

But the original statement is not how `pageLink2`() is intended to be called, although there are lots of instances of how that is done and maybe you copied one of those. The first parameter is the page name only, any further parameters for the URL should be in the `$url` parameter

    PageLink2('processbounces', s('Reprocess Only Existing Bounces'), 'justexisting=true', false, s('Reprocess Only Existing Bounces'))

thus having only one hard-coded parameter to `pageLink2()`. There are many calls to PageLink2 that have to hard-code the third or fourth parameters in order to specify the `$title` parameter, so one more should not really be a problem.
Having a version check with two alternate statements seems to be a worse solution as it has both the _modern_ and _old_ lines of code.

2024-03-11 18:35 UTC, lwcorp commented
> There is a syntax error in the latest change.

No, there wasn't ,see discussion above, it's phpList's interpreter deciding to ignore v8+ commands even in v8+ mode. In any case, I don't know why would an old approach be better than a dual modern/old approach, but since it matters so much I've changed to just an old approach, thus no "syntax error" now.

You can see [function PageLink2](https://github.com/phpList/phplist3/blob/7832a75f9e306f1d9490433804e032215c8d37c2/public_html/lists/admin/connect.php#L1158)'s default values are blank for $url and false for $no_plugin. Since passing those values does no harm, I've kept them as such.

2024-03-24 18:34 UTC, michield approved these changes

2024-03-24 18:34 UTC, michield commented
I think this can be merged into the next release.

2024-03-28 14:10 UTC, merged