Bounces' subscriber' status indicator + allowing to confirm right from bounces
phpList/phplist3 pull request #1029
Opened 2024-03-05 21:13 UTC by lwcorp

## Description
1. Added confirmed/blacklisted indicator on View bounces
1. Added confirmed/blacklisted indicator on View bounces by list
1. Added confirmed/blacklisted indicator on View a bounce
1. Allowed to confirm right from View a bounce (made sure the checkbox doesn't allow checking both to unconfirm and confirm at the same time)

## Screenshots (if appropriate):
![image](https://github.com/phpList/phplist3/assets/1773306/a5d328a1-a789-4a93-a366-ff557897a891)
![image](https://github.com/phpList/phplist3/assets/1773306/9e7e4056-df87-4368-8d5c-5b108ed06dce)
![image](https://github.com/phpList/phplist3/assets/1773306/74dc9a4c-f903-422f-9904-efd5db6f2ed5)

2024-03-09 11:28 UTC, michield requested changes
`$GLOBALS['I18N']->get('text')`

and 

`s('text')`

are basically the same. Older code still uses the `$GLOBALS['I18N']->get` but any code that is touched should change that to using `s`

2024-03-09 11:28 UTC, michield commented on public_html/lists/admin/bounce.php
> +        $actionresult .= sprintf($GLOBALS['I18N']->get('Made subscriber %s ' . ($confirm ? '' : 'un') . 'confirmed').'<br />', $userid);
This won't work with the translation system. It can handle "sprintf" type constructions, but not the `$confirm ? '' : 'un'`

Instead it'll need to be 

```
if ($confirm)
   confirm text
elseif ($unconfirm)
  unconfirm text

```

2024-03-09 11:28 UTC, michield commented on public_html/lists/admin/listbounces.php
> +            if ($userdata['confirmed'] && !isBlackListed(htmlspecialchars($userdata['email'])))
I know one-line IFs work, but it's neater to add curly brackets.

2024-03-10 09:13 UTC, michield requested changes
Few small final tweaks

2024-03-10 09:13 UTC, michield commented on public_html/lists/admin/bounce.php
> +    $actionpanel .= '<tr><td>'.s('Mark subscriber as unconfirmed').'<br />'.s('(so you can resend the request for confirmation)').'<br />or confirmed'.'<br />'.s('(so you can revert possible auto unc
"or confirmed" cannot be translated this way. Also, like that it's going to be quite hard to translate, as it's pulled out of context. Preferably you'd make the entire sentence a string that can be translated, instead of split up into sub-sentences.

Also, seems a bit convoluted to use checkboxes and tweak it with JS to act like radio buttons. But I guess it works, so not a big one.

2024-03-10 23:58 UTC, lwcorp commented on public_html/lists/admin/bounce.php
> +    $actionpanel .= '<tr><td>'.s('Mark subscriber as unconfirmed').'<br />'.s('(so you can resend the request for confirmation)').'<br />or confirmed'.'<br />'.s('(so you can revert possible auto unc
I didn't use translation there since there was none, but I guess it should be done, since it'll just fallback onto itself which is better than no translation, so done.

As for checkboxes, just noting it was done deliberately since radio buttons would have required a third radio button of "none", and this both take unneeded space and risk breaking stuff due to throwing a whole new value.

2024-03-24 18:36 UTC, michield commented
Marked ready to merge

2024-03-30 14:46 UTC, michield approved these changes

2024-03-30 15:40 UTC, merged