Avoid sql error when importing a file with the wrong field delimiter
phpList/phplist3 pull request #712
Opened 2020-11-18 10:21 UTC by bramley

## Description

This forum topic  https://discuss.phplist.org/t/attributes-not-working-on-import/6768 showed an sql error when trying to import a comma separated file but not changing the field separator from TAB. This change escapes the column name when trying to match it with an attribute name.
## Related Issue

## Screenshots (if appropriate):

2020-11-18 11:35 UTC, michield commented
The build fails on Chrome, but that can be ignored.

We should also try to detect that there's an invalid delimiter used, and either give a warning or suggestion of a different delimiter, but I guess that's slightly more work.

2020-11-18 21:29 UTC, bramley commented
I had thought about trying to identify an incorrect field delimiter. I think that the most likely case is someone importing a file with comma or semi-colon separator (i.e. not tab). In this case each line will be treated as just one field. So if the number of columns in the first row of headers is exactly 1 then we could issue a warning when the user is asked to match unidentified column headers.

If there really is only one field in the file then that has to be the email address, so the header column value should be matched automatically and the warning would not be issued.
Maybe something like this

        if (count($headers) == 1) {
            printf('<p class="information">%s</p>', s('The entered field delimiter might not be correct'));
        }


![image](https://user-images.githubusercontent.com/3147688/99589501-f9c9d080-29e3-11eb-8369-99ce77e41f6e.png)

2020-11-18 22:37 UTC, michield commented
Yes, that's a great idea. Also, we could check on comma and semi-colon, and then add the option to re-submit with the one that was detected. But the suggested change is a good start.

2020-11-19 18:12 UTC, bramley commented
I have played around a bit and this seems to work reasonably well. The layout seems a bit cluttered though and the message is a bit wordy.

![image](https://user-images.githubusercontent.com/3147688/99706053-71563900-2a92-11eb-9113-b804602a69f9.png)

2020-11-19 22:34 UTC, michield commented
That's brilliant. I think that will definitely improve the UX here. I think it's a common issue, and I've bumped into it a few times myself. 
This will be a great addition.

2020-11-19 22:36 UTC, michield requested changes

2020-11-19 22:36 UTC, michield commented on public_html/lists/admin/import2.php
> +    $_SESSION['import_field_delimiter'] = $_GET['delimiter'];
This needs sanitising though. You can't just take a get and use it.

2020-11-23 17:40 UTC, bramley commented
I have added validation of the GET parameter, and improved the presentation of the message by displaying it within a "note" div.

![image](https://user-images.githubusercontent.com/3147688/99995858-e5565100-2db2-11eb-8377-ab651c51808d.png)

2020-11-23 20:16 UTC, michield commented
That's great, thanks. @marianaballa this is ready to merge

2020-12-04 15:35 UTC, merged